---
- name: install packages
  apt:
    name: [libssl-dev, libffi-dev, python3-dev,
           python3-pip, build-essential, libpq-dev]

- name: create flask group
  group:
    name={{ flaskapp_app_user }}
    state=present

- name: create flask user
  user:
    name={{ flaskapp_app_user }}
    group={{ flaskapp_app_user }}

- name: Create app log directory
  file: dest={{ flaskapp_app_log_directory }} state=directory
