---
- name: Admin
  include: admin.yml
  when: admin_part
  become: root

- name: Checkout sources
  unarchive:
    dest=/opt
    remote_src=true
    src={{ sources_url }}
    owner={{ flaskapp_app_user }}
    group={{ flaskapp_app_user }}
    validate_certs=no
  register: source_update
  notify: restart app

- name: create symlink to sources
  file:
    dest: "{{ flaskapp_app_directory }}"
    src: "/opt/{{ source_name }}"
    state: link
  when: source_update.changed

- name: config app
  template:
    src=env.j2 dest={{ flaskapp_app_directory }}/.env
    owner={{ flaskapp_app_user }} group={{ flaskapp_app_user }}
    mode=0600
  notify: restart app

- name: Checkout static
  unarchive:
    dest={{ flaskapp_app_directory }}
    remote_src=true
    src={{ static_url }}
    owner={{ flaskapp_app_user }}
    group={{ flaskapp_app_user }}
    validate_certs=false
  when: static

- name: install requirements via pipenv
  include: pipenv.yml
  when: venv_lib == pipenv

- name: install requirements via pipenv
  include: pipenv.yml
  when: venv_lib == pipenv

- name: app
  include: webapp.yml
  when: webapp

- name: worker
  include: worker.yml
  when: worker

- name: scheduler
  include: scheduler.yml
  when: scheduler
