---
- name: Upgrade pip
  pip:
    name: [pip, wheel]
    virtualenv: "{{ flaskapp_app_directory }}/venv"
    virtualenv_command: pyvenv

# TODO костыль из-за глюка setuptools
- name: Install Flask
  pip:
    name: [Flask]
    virtualenv: "{{ flaskapp_app_directory }}/venv"
    virtualenv_command: pyvenv

- name: Install app package
  shell:
    cmd: "source venv/bin/activate && python3 setup.py install"
    chdir: "{{ flaskapp_app_directory }}"
  args:
    executable: /bin/bash
  when: source_update.changed

- name: migrate db structure
  shell: |
    cd {{ flaskapp_app_directory }}
    source venv/bin/activate
    flask db upgrade
  args:
    executable: /bin/bash
  environment:
    FLASK_APP: "{{ flask_app }}.py"
  when: migrate
  notify: restart app
  become: "{{ flask_user }}"
