---
- name: set variables for webapp
  set_fact:
    command: "{{ webapp_command }}"
    numprocs: 1

- name: Ensure supervisor config for app
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/{{ flaskapp_app_name }}.conf
  notify: restart supervisor
