---
- name: set variables for webapp
  set_fact:
    command: "{{ webapp_command }}"

- name: Copy run script
  template:
    src: run.sh.j2
    dest: "{{ flaskapp_app_directory }}/run_{{ flaskapp_app_name }}.sh"
    mode: a+x
  notify: restart supervisor

- name: Ensure supervisor config for app
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/{{ flaskapp_app_name }}.conf
  notify: restart supervisor
