---
- name: set variables for worker
  set_fact:
    flaskapp_app_name: 'worker'
    command: "{{ worker_command }}"
    numprocs: 2

- name: Ensure supervisor config for app
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/{{ flaskapp_app_name }}.conf
  notify: restart supervisor
